import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { 
  Mic, 
  MessageSquare, 
  Search, 
  Cpu, 
  Video, 
  Code, 
  Mail, 
  Globe 
} from 'lucide-react';
import './Landing.css';

const Landing = () => {
  const fadeInUp = {
    initial: { opacity: 0, y: 30 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.6, ease: "easeOut" }
  };

  const staggerContainer = {
    animate: {
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const features = [
    {
      icon: <Mic size={24} />,
      title: "Real-time Transcription",
      description: "Experience crystal clear, lightning-fast transcription for every meeting with 99% accuracy across 50+ languages."
    },
    {
      icon: <MessageSquare size={24} />,
      title: "AI Meeting Summaries",
      description: "Get concise, action-oriented summaries of your meetings automatically generated by our advanced LLM engine."
    },
    {
      icon: <Search size={24} />,
      title: "Semantic Search",
      description: "Search through your meeting history using concepts and intent, not just keywords. Find exactly what was discussed."
    },
    {
      icon: <Cpu size={24} />,
      title: "Meeting Chatbots",
      description: "Each meeting gets a dedicated AI chatbot that knows everything discussed and can answer your questions instantly."
    }
  ];

  return (
    <div className="landing-container">
      {/* Background Glows */}
      <div className="bg-glow">
        <div className="glow-circle glow-1"></div>
        <div className="glow-circle glow-2"></div>
      </div>

      {/* Navbar */}
      <nav className="navbar">
        <div className="nav-logo">
          <span>GetAiFor</span>
        </div>
        <div className="nav-auth">
          <Link to="/login" className="nav-link">Login</Link>
          <Link to="/register" className="btn-register">Get Started</Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="hero">
        <motion.div 
          className="hero-badge"
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
        >
          Next Generation AI Conferencing
        </motion.div>
        
        <motion.h1 
          className="hero-title"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
        >
          Meetings that <br /> <span>think for you.</span>
        </motion.h1>

        <motion.p 
          className="hero-subtitle"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 0.4 }}
        >
          Supercharge your collaboration with real-time transcription, 
          automated summaries, and AI-powered meeting intelligence.
        </motion.p>

        <motion.div 
          className="hero-ctas"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.6 }}
        >
          <Link to="/register" className="btn-primary">Get Started Free</Link>
          <Link to="/about" className="btn-secondary">Learn More</Link>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="features">
        <div className="section-header">
          <motion.h2 
            className="section-title"
            {...fadeInUp}
          >
            Powerful Features
          </motion.h2>
        </div>

        <motion.div 
          className="features-grid"
          variants={staggerContainer}
          initial="initial"
          whileInView="animate"
          viewport={{ once: true }}
        >
          {features.map((feature, index) => (
            <motion.div 
              key={index} 
              className="feature-card"
              variants={fadeInUp}
            >
              <div className="feature-icon">
                {feature.icon}
              </div>
              <h3>{feature.title}</h3>
              <p>{feature.description}</p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-content">
          <div className="footer-brand">
            <h2>GetAiFor</h2>
            <p>The world's most advanced AI-powered conferencing platform for modern teams.</p>
          </div>
          
          <div className="footer-links">
            <div className="footer-column">
              <h4>Product</h4>
              <ul>
                <li><a href="#">Features</a></li>
                <li><a href="#">Pricing</a></li>
                <li><a href="#">Security</a></li>
              </ul>
            </div>
            <div className="footer-column">
              <h4>Company</h4>
              <ul>
                <li><a href="#">About</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Careers</a></li>
              </ul>
            </div>
            <div className="footer-column">
              <h4>Connect</h4>
              <div style={{ display: 'flex', gap: '1rem' }}>
                <a href="#"><Mail size={20} /></a>
                <a href="#"><Globe size={20} /></a>
                <a href="#"><Code size={20} /></a>
              </div>
            </div>
          </div>
        </div>
        
        <div className="footer-bottom">
          <p>&copy; 2026 GetAiFor. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
